/* Generated by TinyC+. Inspectable C11; do not edit. */
#include "tiny_runtime.h"
typedef int32_t (*tc_func_68)(void);
typedef int32_t (*tc_func_67)(int32_t);
typedef void (*tc_func_66)(int32_t);
typedef void (*tc_func_65)(void *);
typedef void * (*tc_func_64)(void *, uint64_t);
typedef void * (*tc_func_63)(uint64_t, uint64_t);
typedef void * (*tc_func_62)(uint64_t);
typedef struct { int32_t data[3]; } tc_array_37;
void * malloc(uint64_t size);
void * calloc(uint64_t count, uint64_t size);
void * realloc(void * pointer, uint64_t size);
void free(void * pointer);
void exit(int32_t code);
int32_t tc_f_21_record(int32_t tc_v_22_value);
int32_t tc_user_main(void);
int32_t tc_f_21_record(int32_t tc_v_22_value)
{
    #line 1 "<source>"
    int32_t tc_tmp_1 = tc_v_22_value;
    tc_print_integer(tc_tmp_1, 1);
    #line 1 "<source>"
    int32_t tc_tmp_2 = tc_v_22_value;
    return tc_tmp_2;
}

int32_t tc_user_main(void)
{
    #line 3 "<source>"
    #line 4 "<source>"
    int32_t tc_tmp_3 = 1;
    int32_t tc_tmp_4 = 2;
    int32_t tc_tmp_5 = 3;
    tc_array_37 tc_v_36_values = (tc_array_37){{tc_tmp_3, tc_tmp_4, tc_tmp_5}};
    #line 5 "<source>"
    {
        int32_t * tc_tmp_6 = (tc_v_36_values).data;
        uint64_t tc_v_69_index = 0;
        for (;;) {
            if (tc_v_69_index >= 3) break;
            int32_t tc_v_70_value = tc_tmp_6[tc_v_69_index];
            {
                #line 6 "<source>"
                #line 7 "<source>"
                int32_t tc_tmp_8 = tc_v_70_value;
                int32_t tc_tmp_9 = 2;
                bool tc_tmp_10 = (tc_tmp_8 == tc_tmp_9);
                if (tc_tmp_10)
                {
                    #line 7 "<source>"
                    uint64_t tc_tmp_11 = tc_v_69_index;
                    tc_print_unsigned(tc_tmp_11, 1);
                    goto tc_continue_7;
                }
                #line 8 "<source>"
                int32_t tc_tmp_12 = tc_v_70_value;
                tc_f_21_record(tc_tmp_12);
                uint64_t tc_tmp_13 = tc_v_69_index;
                tc_print_unsigned(tc_tmp_13, 1);
            }
            tc_continue_7:;
            ++tc_v_69_index;
        }
        tc_break_7:;
    }
    #line 10 "<source>"
    int32_t tc_tmp_14 = 0;
    int32_t tc_tmp_15 = tc_f_21_record(tc_tmp_14);
    int32_t tc_tmp_16 = 9;
    tc_print_integer(tc_tmp_16, 1);
    return tc_tmp_15;
    int32_t tc_tmp_17 = 9;
    tc_print_integer(tc_tmp_17, 1);
    return 0;
}

int main(int argc, char **argv) {
    tc_program_argc = argc; tc_program_argv = argv;
    int result = tc_user_main();
    if (tc_program_cleanup) tc_program_cleanup();
    return result;
}
