/* Generated by TinyC+. Inspectable C11; do not edit. */
#include "tiny_runtime.h"
typedef int32_t (*tc_func_74)(int32_t, int32_t);
typedef int32_t (*tc_func_72)(int32_t);
typedef struct { void *env; bool (*invoke)(void *, int32_t); bool owned; } tc_func_70;
typedef int32_t (*tc_func_67)(void);
typedef void (*tc_func_66)(int32_t);
typedef void (*tc_func_65)(void *);
typedef void * (*tc_func_64)(void *, uint64_t);
typedef void * (*tc_func_63)(uint64_t, uint64_t);
typedef void * (*tc_func_62)(uint64_t);
typedef struct { int32_t data[4]; } tc_array_24;
int32_t tc_user_main(void);
struct tc_env_40 {
    int32_t capture_30;
};
static bool tc_lambda_40(void *tc_environment, int32_t tc_v_41_value) {
    struct tc_env_40 *tc_env = (struct tc_env_40 *)tc_environment;
    int32_t tc_tmp_1 = tc_v_41_value;
    int32_t tc_tmp_2 = tc_env->capture_30;
    return (tc_tmp_1 > tc_tmp_2);
}
static int32_t tc_lambda_48(int32_t tc_v_49_value) {
    int32_t tc_tmp_3 = tc_v_49_value;
    int32_t tc_tmp_4 = 2;
    return (tc_tmp_3 * tc_tmp_4);
}
static int32_t tc_lambda_56(int32_t tc_v_57_total, int32_t tc_v_58_value) {
    int32_t tc_tmp_5 = tc_v_57_total;
    int32_t tc_tmp_6 = tc_v_58_value;
    return (tc_tmp_5 + tc_tmp_6);
}
int32_t tc_user_main(void)
{
    #line 2 "<source>"
    int32_t tc_tmp_7 = 1;
    int32_t tc_tmp_8 = 2;
    int32_t tc_tmp_9 = 3;
    int32_t tc_tmp_10 = 4;
    tc_array_24 tc_v_23_values = (tc_array_24){{tc_tmp_7, tc_tmp_8, tc_tmp_9, tc_tmp_10}};
    #line 3 "<source>"
    int32_t tc_v_30_threshold = 2;
    #line 4 "<source>"
    int32_t * tc_tmp_11 = (tc_v_23_values).data;
    struct tc_env_40 tc_tmp_12 = {0};
    (&tc_tmp_12)->capture_30 = tc_v_30_threshold;
    tc_func_70 tc_tmp_13 = (tc_func_70){&tc_tmp_12, tc_lambda_40, 0};
    tc_func_72 tc_tmp_15 = tc_lambda_48;
    int32_t tc_tmp_17 = 0;
    int32_t tc_tmp_16 = tc_tmp_17;
    tc_func_74 tc_tmp_19 = tc_lambda_56;
    uint64_t tc_tmp_20 = 0;
    /* Fused stream: one traversal, no intermediate collections. */
    for (; tc_tmp_20 < 4; ++tc_tmp_20) {
        int32_t tc_tmp_21 = tc_tmp_11[tc_tmp_20];
        if (!(tc_tmp_13.invoke(tc_tmp_13.env, tc_tmp_21))) continue;
        int32_t tc_tmp_22 = tc_tmp_15(tc_tmp_21);
        tc_tmp_16 = tc_tmp_19(tc_tmp_16, tc_tmp_22);
    }
    int32_t tc_tmp_23 = tc_tmp_16;
    tc_print_integer(tc_tmp_23, 1);
    return 0;
}

int main(int argc, char **argv) {
    tc_program_argc = argc; tc_program_argv = argv;
    int result = tc_user_main();
    if (tc_program_cleanup) tc_program_cleanup();
    return result;
}
